name: Build and Test
on: [pull_request, workflow_dispatch, push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build 
        run: make build 
      - name: Test
        run: make test
