name: Build and Test
on: [pull_request, workflow_dispatch, push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Build 
        run: make build 
      - name: Test
        run: |
          go get github.com/onsi/ginkgo/v2/ginkgo
          make test
