name: Lint
on: [pull_request, workflow_dispatch]
jobs:
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2
          make lint
